### ISSUE TITLE
Verify line numbering

### ISSUE THREAD

**Issue by oxr463** [neverrend/XMLChecker#3]
Test case

```
1.

2.

4.
```

**Comment by neverrend** [comment]
Closing this. Latest commit added this. Probably needs to be tested a bunch since everyone does it a little differently. Standard way that Andrew generates this is like this "1." but the current regex will catch numbers like "1)". Probably want to add something to tell you if you have used one way over another on a flaw or in the document..

**Comment by eredisg** [comment]
It appears that this is still an issue. It was ran on the following line numbers but it was not caught:
```
1)

2)

2) ...etc
```

**Comment by neverrend** [comment]
@eredisg send me the code block and ill take a look at it. Idk if it has something to do with the ) vs . but it shouldn't.

**Comment by neverrend** [comment]
Fixed with 9a70b0e.
